import type { Metadata } from "next";
import "./globals.css";
import { HeaderSection } from "@/components/common/HeaderSection";
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { ClientThemeProvider } from '@/components/common/ClientThemeProvider';
import { fontVariables } from '@/lib/font';
import { cn } from '@/lib/utils';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeThemeValue = cookieStore.get('active_theme');
  const isScaled = cookieStore.get('is_scaled');
  
  return (
    <html lang="en">
      <body
          className={cn(
            'bg-background overscroll-y-auto font-sans antialiased',
            activeThemeValue ? `theme-${activeThemeValue}` : '',
            isScaled ? 'theme-scaled' : '',
            fontVariables
          )}
      >
        <ClerkProvider appearance={{
          baseTheme: dark,
        }}>
          <ClientThemeProvider>
            <HeaderSection />
            {children}
          </ClientThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
